# Generated by Django 3.1.5 on 2021-01-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmcatapp', '0005_movie_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='seen',
            new_name='seen_by',
        ),
    ]
